package br.com.yolo.core.player.account.setting;

public enum SettingTag {

    CHAT_MESSAGES,
    PRIVATE_MESSAGES,
    ALERT_MESSAGES,
    PARTY_INVITATIONS,
    PARTY_MESSAGES,
    STAFF_MESSAGES,
    STAFF_CHAT_MODE,
    CLAN_INVITATIONS,
    CLAN_MESSAGES,
    CLAN_CHAT_MODE,
    FRIEND_INVITATIONS,
    HIDE_STATISTICS,
    AUTO_JOIN_VANISHED,
    HIDE_LOBBY_PLAYERS,

    ACCOUNT_PASSWORD,
    NICKNAME,
    BUILDING,
    REEMDEMED_TRIAL_VIP,
    LAST_IP_ADDRESS,
    FIRST_LOGGED_IN,
    LAST_LOGGED_IN,
    COINS,

    TWITTER,
    YOUTUBE_CHANNEL,
    INSTAGRAM,
    TWITCH,
    TIKTOK,
    DISCORD;
}
