package br.com.yolo.core.account.statistic;

public enum StatisticTag {

    REGISTERED_BAN_PUNISHMENTS,
    REGISTERED_SILENT_PUNISHMENTS,

    PVP_RATING,

    PVP_ARENA_KILLS,
    PVP_ARENA_DEATHS,
    PVP_ARENA_KS,
    PVP_ARENA_GREATER_KS,

    PVP_FPS_KILLS,
    PVP_FPS_DEATHS,
    PVP_FPS_KS,
    PVP_FPS_GREATER_KS,

    DUELS_SOUP_RATING,
    DUELS_SOUP_MATCHES,

    DUELS_SOUP_1V1_WINS,
    DUELS_SOUP_1V1_LOSSES,
    DUELS_SOUP_1V1_KS,
    DUELS_SOUP_1V1_GREATER_KS,

    DUELS_SOUP_2V2_WINS,
    DUELS_SOUP_2V2_LOSSES,
    DUELS_SOUP_2V2_KS,
    DUELS_SOUP_2V2_GREATER_KS,

    DUELS_GLAD_RATING,
    DUELS_GLAD_MATCHES,

    DUELS_GLAD_1V1_WINS,
    DUELS_GLAD_1V1_LOSSES,
    DUELS_GLAD_1V1_KS,
    DUELS_GLAD_1V1_GREATER_KS,

    DUELS_GLAD_2V2_WINS,
    DUELS_GLAD_2V2_LOSSES,
    DUELS_GLAD_2V2_KS,
    DUELS_GLAD_2V2_GREATER_KS,

    HG_RATING,
    HG_SINGLEKIT_WINS,
    HG_MULTIKIT_WINS,
    HG_SINGLEKIT_KILLS,
    HG_MULTIKIT_KILLS,
    HG_SINGLEKIT_DEATHS,
    HG_MULTIKIT_DEATHS,
    HG_SINGLEKIT_ASSISTS,
    HG_MULTIKIT_ASSISTS;
}
